In [10]:
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn import model_selection

In [13]:
cancer_ds = datasets.load_breast_cancer()
cancer_ds.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [14]:
clf = LogisticRegression()
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(cancer_ds.data, cancer_ds.target)

In [15]:
clf.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [16]:
clf.predict(X_test)

array([1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1])

In [18]:
clf.predict_proba(X_test)

array([[2.80940423e-04, 9.99719060e-01],
       [9.86732003e-01, 1.32679971e-02],
       [6.36265068e-04, 9.99363735e-01],
       [8.81731051e-03, 9.91182689e-01],
       [1.74987315e-03, 9.98250127e-01],
       [5.05992188e-02, 9.49400781e-01],
       [1.46886780e-02, 9.85311322e-01],
       [1.55534346e-03, 9.98444657e-01],
       [9.99999626e-01, 3.73901919e-07],
       [9.26377637e-01, 7.36223630e-02],
       [4.19333522e-01, 5.80666478e-01],
       [1.73047013e-02, 9.82695299e-01],
       [4.00350741e-03, 9.95996493e-01],
       [9.99976963e-01, 2.30370014e-05],
       [8.49512399e-01, 1.50487601e-01],
       [2.27882333e-03, 9.97721177e-01],
       [1.96285933e-03, 9.98037141e-01],
       [9.73398951e-01, 2.66010493e-02],
       [9.90571094e-01, 9.42890609e-03],
       [1.56257430e-01, 8.43742570e-01],
       [1.20626379e-03, 9.98793736e-01],
       [2.10424241e-02, 9.78957576e-01],
       [2.61652757e-03, 9.97383472e-01],
       [1.00556873e-03, 9.98994431e-01],
       [5.928384

In [21]:
clf.score(X_train, Y_train)

0.9553990610328639

In [23]:
clf.predict(X_test) - Y_test

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,
        0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,
        0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0])

In [28]:
Y_pred = clf.predict(X_test)
print(Y_pred)
import numpy as np
np.savetxt("Cancer_predictions_LogReg.csv", Y_pred)

[1 0 1 1 1 1 1 1 0 0 1 1 1 0 0 1 1 0 0 1 1 1 1 1 1 1 1 1 0 0 1 0 0 1 1 1 1
 0 0 0 0 1 0 0 0 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 0 0 0 0 1 1 1 0 1 1 1
 1 1 1 1 0 1 0 0 0 1 1 1 0 1 1 0 1 0 1 0 0 1 1 0 1 0 0 1 0 0 1 1 1 1 1 1 1
 1 0 0 1 1 0 0 0 0 0 1 0 1 0 0 1 1 0 1 0 1 1 0 1 1 1 0 1 1 0 0 1]
